### PR TITLE
Update to use agent model

### PR DESCRIPTION
**Pull request by adrianhopebailie**

### CODE REVIEW

**Comment by sharafian** [comment]
Could you fix the line-width formatting? Every line appears to be changed so it's hard to see what's a diff and what's a reformat

**Comment by sublimator** [comment]
Maybe `prettier` can help with that?

**Comment by adrianhopebailie** [comment]
> Could you fix the line-width formatting? Every line appears to be changed so it's hard to see what's a diff and what's a reformat

Yeh, I started using `prettier` to fix the line width. Unfortunately means it will be hard this time.

The rich diff is easier to review.

**Comment by marcoscaceres** [comment]
We can plug in HTML tidy, like we do with other specs... also works well. But I agree, it seems like a lot of changes... might take a little while to review.

**Comment by adrianhopebailie** [comment]
Most of the wording changes relate to this updated flow so start by just checking this and letting me know what you think:

image

**Review by brucelawson — COMMENTED** [review]
- does it matter that we call it Web Mon Sender here, and 'payment provider' elsewhere in our materials. (prolly not, imo)

In sending.md, link "Payment Handler API" to the relevant spec

**Comment by adrianhopebailie** [comment]
> * does it matter that we call it Web Mon Sender here, and 'payment provider' elsewhere in our materials. (prolly not, imo)
> 
> In sending.md, link "Payment Handler API" to the relevant spec

@brucelawson I just made a big update to the `sending` page to fully explain how we would use Payment Handler

**Comment by brucelawson** [comment]
Aha! LGTM

**Pull request merged**
